version: '3.7'

services:
  cucumberchat:
    build: .
    image: butteff/samples:cucumber-chat
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redisss:6379/1
    restart: always
    container_name: cucumber_chat
    ports:
      - 3000:3000
    volumes:
      - ./storage/:/rails/storage/
    depends_on: 
      - redisss
    links: 
      - redisss

  redisss:
    image: redis:latest
    restart: always
    container_name: cucumber_redis
    ports:
      - 0.0.0.0:6379:6379
    volumes:
    - type: volume
      source: redis
      target: /data
    
volumes:
  redis: